### ISSUE TITLE
The repository needs to be trimmed. Current size: 1GB+

### ISSUE THREAD

**Issue by MattGuerrette** [Honeybunch/Brickware-Engine#12]
The repo needs to be trimmed to reduce clone time. At over 1GB it takes a significant amount of time.

**Comment by Honeybunch** [comment]
Yes I'm aware of the problem but was unable to clean it out over the summer due to time constraints. It's one of the first things on the chopping block once I get re settled from my move.

**Comment by Honeybunch** [comment]
Cleaned with BFG. Size should only be around 116 MB. Want to clone and confirm?

**Comment by MattGuerrette** [comment]
Yes, it is now around 116 MB.
