### ISSUE TITLE
Linux build fails to run with core dump.

### ISSUE THREAD

**Issue by MattGuerrette** [Honeybunch/Brickware-Engine#13]
{
    0
    hello
    100
    10.5
    0
        1025
        world
    [1,2,3,10,20,]
    {
        index:0
    },
    {
        index:1
    },
}

**\* Error in `./BrickwareTest': free(): invalid next size (fast): 0x0000000001fe79b0 ***
Aborted (core dumped)

**Comment by Honeybunch** [comment]
Build should succeed and even run most of the time. There is a bit of a race condition that I am investigating but progress is made. See #11

**Comment by Honeybunch** [comment]
This was caused by some weird heap corruption issues that have now been fixed in 61bfd94d65040f911d634c28d40c38afc001853c
