### ISSUE TITLE
Texture class

### ISSUE THREAD

**Issue by Honeybunch** [Honeybunch/Brickware-Engine#4]
Textures need to not be handled with SOIL since DirectX support is a thing now.
A BMP loader would probably be easiest but PNG seems reasonable too since texture compression is a good idea

**Comment by MattGuerrette** [comment]
I currently use FreeImage. It works quite well and offers easy support for loading from raw streams. It is also open source. The source is in my repo is you want to take a look.

**Comment by Honeybunch** [comment]
I'm looking at trimming this down to a no-library project (save for obvious system libraries)

Loading BMPs is pretty straightforward so I'm not too worried.
